version: "3.0"

services:
  fastapi_tutorial:
    image: fastapi_tutorial
    container_name: fastapi_tutorial
    build:
      context: ..
      dockerfile: ./docker/Dockerfile
    user: dev
    volumes:
      - ..:/usr/src/app
    ports:
      - 8080:8080
    tty: true
