version: "3.0"

services:
  fastapi_tutorial:
    image: fastapi_tutorial
    container_name: fastapi_tutorial
    build:
      context: ..
      dockerfile: ./docker/api/Dockerfile
    user: dev
    volumes:
      - ..:/usr/src/app
    ports:
      - 8080:8080
    tty: true
  
  fastapi_tutorial_db:
    image: fastapi_tutorial_db
    container_name: fastapi_tutorial_db
    build:
      context: ..
      dockerfile: ./docker/mysql/Dockerfile
    environment:
      MYSQL_DATABASE: main
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    tty: true
